[project]
name = "backend-python"
version = "0.1.0"
description = "Fetch GitHub issues and store them in a [Supabase|SQLite] database."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pydantic>=2.11.10",
    "requests>=2.32.5",
    "supabase>=2.21.1",
]
